version: '3.8'

services:
  nginx:
    build: .
    image: rafazaychick/meu-nginx-personalizado:latest
    container_name: rafael-nginx
    ports:
      - "8080:80"
    restart: unless-stopped